#!/bin/bash

test_dir="test-$1"
shift

cd hardlink-test-daten || exit 1

rm -fr 'test'
cp -r  "$test_dir" 'test'

../hardlink.py 'test' "$@"

echo "here comes the diff"
diff -r 'test' "$test_dir"
echo "end of diff diff"

