#!/bin/bash

test_dir="test-${1:-small}"
shift

cd hardlink-test-daten || exit 1

rm -fr 'test'
echo -n 'copy test files ...'
cp -r  "$test_dir" 'test' || exit 1
echo 'done'
echo

echo "### running hardlink #####################"
../hardlink.py -s -v 'test' "$@"
echo "### running hardlink - done ##############"

echo "here comes the diff"
diff -r --no-dereference 'test' "$test_dir"
echo "end of diff diff"

